### ISSUE TITLE
README記入-使用技術-

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#104]
自分の担当部分で使用した物をそれぞれコメント

利用したプログラミング言語

利用したフレームワーク・ライブラリ

その他開発に使用したツール

**Comment by Atria64** [comment]
### 利用したプログラミング言語
 - Kotlin
### 利用したフレームワーク・ライブラリ
 - retrofit2
 - GSON
 - welcome-android
 - Google Maps API for Android
### その他開発に使用したツール
 - AndroidStudio
 - GitHub
 - Git Bash
 - Vim

**Comment by t4t5u0** [comment]
## 自分の担当部分で使用した物をそれぞれコメント
- バック
## 利用したプログラミング言語
- Python3
## 利用したフレームワーク・ライブラリ
- SQLite3, Flask
## その他開発に使用したツール
- vim, クラウドサーバ, GitHub

**Comment by materialofmouse** [comment]
## 利用した言語
python3

## 利用したライブラリ
wiringpi

## その他開発に使用したツール
make
vim
systemd
