### ISSUE TITLE
地図の表示

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#13]

**Comment by Atria64** [comment]
Googlemapを使用する方針で行きます。

# 実装したい機能
起動時に**自分の位置を中心として**Google Mapを表示させる
# 必要とされそうな実装
 - 位置情報周りの権限取得
 - 位置情報の取得 #14 
 - Google Mapのムーブ
# 予想される工期
- 権限周り 
  - 2h/人
- 位置情報の取得 #14 
  - 30min/人
- Google Mapのムーブ
  - 30min/人
   
合計約３時間
# 何をもってして達成とするか
起動時に自分の位置を中心としてGoogle Mapが正しく表示されること。
@yuhi-dosei の実機と @Atria64 の実機で検証すること。

**Comment by Atria64** [comment]
Google Map Android API v2を用いて開発します。
ところで、プロジェクトファイル立ち上げる時にマップ簡単に作るやつがあったっぽいですね…

**Comment by Atria64** [comment]
> プロジェクトファイル立ち上げる時にマップ簡単に作るやつ
   
これでやる方針になりました

**Comment by Atria64** [comment]
簡単なマップ表示は成功しました。
#14 に取り掛かります。
![image](https://user-images.githubusercontent.com/49768768/70599991-eccc2b00-1c31-11ea-843e-32b708b6c799.png)

**Comment by Atria64** [comment]
正しくは #73
