### ISSUE TITLE
自分の位置情報を取る

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#14]
権限を取る

**Comment by Atria64** [comment]
# 実装したい機能
自分の位置情報を取る
# 必要とされそうな実装
 - 権限取得
 - バージョンごとの権限周り切り替え
# 予想される工期
1h/人
# 何をもってして達成とするか
自分の位置情報を取得し、表示できた時。(例)緯度経度のトースト表示、標準出力など)

**Comment by Atria64** [comment]
LocationServices API を使用します。
