### ISSUE TITLE
国土交通省の許可画面

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#20]
ex)
あなたは飛ぶサンタですか?
→国土交通省の許可を得ましたか？
いいえ
→あなたは軽車両に分類されます

**Comment by Atria64** [comment]
ex)お酒は飲んでいませんね?
いいえ
 →アプリ強制終了

**Comment by yuhi-dosei** [comment]
途中までやった
スライドつくる

**Comment by Atria64** [comment]
つくった
#112
