### ISSUE TITLE
JSONの形式を決める

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#31]
フロント側で場合分けがしやすいように受け渡しするJSONの形式を決めてしまう

**Comment by yuhi-dosei** [comment]
たつおにJsonがキモいと言われたのでJSONにfix

**Comment by yuhi-dosei** [comment]
接近処理はフロント側でやることとして話を進める

**Comment by yuhi-dosei** [comment]
機器を設置している
→プレゼントが欲しい
とする

**Comment by yuhi-dosei** [comment]
決まったのでClose

**Comment by Atria64** [comment]
![image](https://user-images.githubusercontent.com/49768768/70369432-99d63900-18fc-11ea-9f45-034a2a8a25e6.png)
