### ISSUE TITLE
AppのAPIレベル選定

### ISSUE THREAD

**Issue by Atria64** [p2hacks/teamR04#52]
APIレベルのターゲットをどうするか、一度全員で話し合う。

# 予想される工期
10分程度

# issueのクローズ条件
全員がこのissueに意見を書き込み、見解を統一できた場合にcloseする。

**Comment by yuhi-dosei** [comment]
26-27(Android8.0,8.1)が無難だと思う

**Comment by Atria64** [comment]
ふむ

**Comment by materialofmouse** [comment]
Android studioのインストールしかしなかったのでよくわかりません

**Comment by Atria64** [comment]
たつお「８でいんじゃね」

**Comment by Atria64** [comment]
ってことで推奨は8.0あたりにしましょう
