### ISSUE TITLE
MainActivityの選定

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#53]
master_frontにあるプロジェクは空で作ってしまった
Googleマップの部分がmainに来るように作り直してはどうだろうか？

masterからbranch切って検証用branchを生やす

**Comment by Atria64** [comment]
branchname flont/testを立ててやってみます

**Comment by Atria64** [comment]
一瞬で成功したのでflont/testの方で開発をすすめる事になりそう。(今考えたらフロントtypoしてるね)
dev_frontにプルリクエスト送ろうと思ってます。

**Comment by Atria64** [comment]
結構前に終わってましたclose
