### ISSUE TITLE
git add時にWarningが吐かれる

### ISSUE THREAD

**Issue by Atria64** [p2hacks/teamR04#55]
# git add時に以下の文章の警告が吐かれる。
 > warning: LF will be replaced by CRLF

![image](https://user-images.githubusercontent.com/49768768/70589380-eda19480-1c12-11ea-89ef-438c8f407789.png)
   
対策を講じるべきかどうか知りたい。
   
# web上の参考文献
[git add時のwarning: LF will be replaced by CRLFを消したかった話し](https://qiita.com/ritsuka/items/e4e1b9aa36b83886ae17)

**Comment by Atria64** [comment]
@yuhi-dosei ご意見頂戴したい
とりあえず緊急性はないっぽいので、開発は続行します。

**Comment by materialofmouse** [comment]
改行コードがうんぬんじゃないの？
macとwinでやってるから違うとか？関係なかったらごめん

**Comment by yuhi-dosei** [comment]
あわあわくんの回答通りだと思う

**Comment by Atria64** [comment]
あーこれ改行まわりなのか
無視でいい感じ?
