### ISSUE TITLE
front branchのディレクトリ構成が危ない

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#59]
hard_clientのディレクトリ構成を見ると
back
-必要なfile群
となっている

しかしfront branchは
frontディレクトリを挟まず
直に必要なfile群が置かれている

直さないと最後にfrontとbackをmasterにmergeするときに壊れてしまう
直さないといけない

**Comment by Atria64** [comment]
直さないといけない

**Comment by yuhi-dosei** [comment]
backも危ない
@t4t5u0

**Comment by Atria64** [comment]
#63 で修正。close.
