### ISSUE TITLE
backのディレクトリ構成が危ない

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#60]
hard_clientのディレクトリ構成を見ると
back
-必要なfile群
となっている

しかしback branchは
backディレクトリを挟まず
直に必要なfile群が置かれている

直さないと最後にfrontとbackをmasterにmergeするときに壊れてしまう
直さないといけない

**Comment by yuhi-dosei** [comment]
あわあわくん「ローカルではちゃんと別れてる」

**Comment by materialofmouse** [comment]
マージしたら治るからOK
