### ISSUE TITLE
必要なAssetsの準備

### ISSUE THREAD

**Issue by yuhi-dosei** [p2hacks/teamR04#67]
ボタンに使うアイコン等を描く
@Atria64 必要なアイコンをコメントに書いてくれると嬉しい

**Comment by Atria64** [comment]
順次追加
# Must
 - 設定ボタンのアイコン
 - プレゼントのアイコン
 - 雷、電気のアイコン
# Want
 - アプリアイコン
 - ピンのアイコン
 - WE周り
